name: mun_down
description: "A scalable Video & Audio Downloader app."
publish_to: 'none'
version: 1.5.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Networking
  dio: ^5.8.0+1

  # Dependency Injection
  get_it: ^8.0.3

  # Local Database
  # isar removed as it's not used yet

  # Path & Permissions
  path_provider: ^2.1.5
  permission_handler: ^11.3.1

  # WebView
  webview_flutter: ^4.13.0

  # YouTube Media Extraction
  youtube_explode_dart: ^2.3.9

  # File Actions
  share_plus: ^10.1.4
  open_filex: ^4.5.0

  # Video Player
  video_player: ^2.9.3
  chewie: ^1.8.5

  # Biometric Auth
  local_auth: ^2.3.0
  connectivity_plus: ^6.1.1
  shared_preferences: ^2.3.5
  audio_session: ^0.2.3
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.15

  # App Icon Generation
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpeg"
  adaptive_icon_background: "#141422"
  adaptive_icon_foreground: "assets/icon/app_icon.jpeg"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/